import {
  Banknote,
  Bitcoin,
  CarFront,
  CircleQuestionMark,
  CreditCard,
  Dumbbell,
  Gamepad2,
  Gift,
  GraduationCap,
  HandCoins,
  HandHeart,
  Home,
  Landmark,
  Luggage,
  ShoppingBag,
  ShoppingCart,
  Utensils,
  Wallet,
} from 'lucide-react';
import type { ISelectableIcon } from '@/entities';

export const SELECTABE_ICONS: ISelectableIcon[] = [
  { key: 'heartpulse', Icon: HandHeart },
  { key: 'utensils', Icon: Utensils },
  { key: 'car', Icon: CarFront },
  { key: 'gamepad2', Icon: Gamepad2 },
  { key: 'wallet', Icon: Wallet },
  { key: 'shoppingcart', Icon: ShoppingCart },
  { key: 'shoppingbag', Icon: ShoppingBag },
  { key: 'gift', Icon: Gift },
  { key: 'home', Icon: Home },
  { key: 'luggage', Icon: Luggage },
  { key: 'graduationcap', Icon: GraduationCap },
  { key: 'activity', Icon: Dumbbell },
  { key: 'circlequestionmark', Icon: CircleQuestionMark },
  { key: 'creditcard', Icon: CreditCard },
  { key: 'handcoins', Icon: HandCoins },
  { key: 'landmark', Icon: Landmark },
  { key: 'bitcoin', Icon: Bitcoin },
  { key: 'banknote', Icon: Banknote },
];
